const pages: Record<string, { eyebrow:string; title:string; intro:string; features:string[] }> = {
  "event-technology": { eyebrow:"PRODUCTS & SERVICES", title:"Products & Services", intro:"Our comprehensive range of event technology products and services can be used individually or combined to meet both simple and complex engagement requirements.", features:["Audience engagement technology","Event design & facilitation","End-to-end event delivery"] },
  "event-technology/products": { eyebrow:"OUR TECHNOLOGY", title:"Audience Engagement Technology Products", intro:"Creating and curating engagement for hybrid, virtual and live events.", features:["OpenMeet","OpenVOD","OpenTube"] },
  "openmeet": { eyebrow:"OPENMEET", title:"Elevate your meetings with our next level audience engagement technology", intro:"OpenMeet is our fully supported audience engagement platform for in-person, hybrid and virtual events, with dynamic tools and support across 40 languages.", features:["Browser based & customisable","Live polling and Q&A","Multilingual participation","Detailed analytics"] },
  "openvod": { eyebrow:"OPENVOD", title:"Power-up Your Videos", intro:"Make event video content instantly accessible to busy healthcare professionals using cutting-edge video on-demand search technology.", features:["Intelligent content search","On-demand access","Branded content hubs","Engagement analytics"] },
  "opentube": { eyebrow:"OPENTUBE", title:"Create interactive video content for maximum engagement", intro:"Present and share video content with a fully customisable and measurable immersive experience for digital audiences across the globe.", features:["Interactive video","Global delivery","Custom branding","Measurable engagement"] },
  "event-technology/services": { eyebrow:"WHAT WE DO", title:"Services", intro:"We offer a range of complementary event technology services and engagement tools to support our core products.", features:["Agenda design","Event registration & microsites","Content development","Events communications","Analytics & insights","Production support"] },
  "event-technology/solutions": { eyebrow:"SOLUTIONS", title:"Solutions", intro:"We are always committed to achieving the best possible outcomes for our clients.", features:["Live events","Hybrid programmes","Virtual meetings","Global congresses","Advisory boards","Internal communications"] },
  "events/life-sciences": { eyebrow:"LIFE SCIENCES", title:"Better engagement for healthcare professionals, globally.", intro:"We design and deliver meetings, congresses, and educational events that give HCPs a voice, ensure compliance, and create measurable outcomes across 150+ markets.", features:["Compliant engagement","HCP education","Advisory boards","Congress support","Global reach","Measurable outcomes"] },
  "sustainability-at-open-audience": { eyebrow:"OUR RESPONSIBILITY", title:"Sustainability at Open Audience", intro:"As a virtual agency with a low carbon footprint, delivering global events virtually, we are always looking at ways to minimise our impact.", features:["Virtual-first working","Lower travel impact","Sustainable event design","Responsible suppliers"] },
  "blog": { eyebrow:"IDEAS & INSIGHTS", title:"Open Audience Blogs", intro:"Our opinions, perspectives and insights.", features:["Rethinking Business and Event Travel","Navigating the Green Wave","To AI or not to AI","Creating Engaging Digital Experiences","All Registration Experiences are Created Equal, Right?","Is post-event viewing now in demand?"] },
  "case-studies": { eyebrow:"OUR WORK", title:"Case Studies", intro:"Explore how we help organisations create inclusive, interactive and measurable audience experiences.", features:["Live Surgery Workshops","Global Pharmaceutical Virtual Briefings","Virtual Advisory Board with Pre-Event Survey","Global Asset Management Conference","Multilingual engagement programmes","Hybrid medical education"] },
  "contact": { eyebrow:"LET'S TALK", title:"Contact Us", intro:"Tell us about your audience engagement challenge and our team will get back to you.", features:["+44 (0) 1296 294136","info@openaudience.com","LinkedIn: Open Audience"] },
};

function Header(){return <header className="site-header"><a className="brand" href="/"><span className="brand-mark"><i/><i/><i/><i/></span><span>Open Audience</span></a><nav aria-label="Primary navigation"><div className="nav-group"><a href="/event-technology/">Products &amp; Services</a><div className="dropdown"><a href="/event-technology/products/">Products</a><a href="/openmeet/">OpenMeet</a><a href="/openvod/">OpenVOD</a><a href="/opentube/">OpenTube</a><a href="/event-technology/services/">Services</a></div></div><a href="/event-technology/solutions/">Solutions</a><a href="/events/life-sciences/">Life Sciences</a><div className="nav-group"><a href="#">More</a><div className="dropdown"><a href="/sustainability-at-open-audience/">Sustainability</a><a href="/blog/">Blog</a><a href="/case-studies/">Case Studies</a></div></div><a href="/contact/">Contact</a></nav><a className="mobile-contact" href="/contact/">Contact</a></header>}
function Footer(){return <footer><div className="section footer-grid"><div><a className="brand brand-white" href="/"><span className="brand-mark"><i/><i/><i/><i/></span><span>Open Audience</span></a></div><div><h4>Sign up for our newsletter</h4><a href="mailto:info@openaudience.com?subject=Newsletter%20sign-up">Sign up →</a></div><div><h4>Links</h4><a href="#">Privacy Policy</a><a href="#">Cookies Policy</a></div><div><h4>Contact</h4><a href="tel:01296294136">+44 (0) 1296 294136</a><a href="mailto:info@openaudience.com">info@openaudience.com</a></div></div><div className="copyright section">© Open Audience 2026</div></footer>}

export default async function ContentPage({params}:{params:Promise<{slug:string[]}>}){
  const key=(await params).slug.join("/"); const page=pages[key]||pages["event-technology"];
  return <main><Header/><section className="inner-hero"><div className="section"><p className="eyebrow light">{page.eyebrow}</p><h1>{page.title}</h1><p>{page.intro}</p><a className="button button-light" href="/contact/">Book a Consultation</a></div></section><section className="section content-section"><p className="eyebrow">HOW WE CAN HELP</p><h2>Engagement designed around your audience</h2><div className="feature-grid">{page.features.map((f,i)=><article key={f}><span>0{i+1}</span><h3>{f}</h3><p>Thoughtfully designed, expertly supported and tailored to your objectives.</p></article>)}</div></section><section className="contact-banner"><div className="section contact-inner"><p className="eyebrow light">CONTACT US</p><h2>Book a<br/>conversation today</h2><p>We would love to talk to you about your audience engagement challenges</p><a className="button button-blue" href="mailto:info@openaudience.com">Get in touch</a></div></section><Footer/><input className="cookie-toggle" type="checkbox" id="cookie-dismiss"/><aside className="cookie-banner"><div><strong>Your privacy matters</strong><p>We use essential cookies to make this website work and optional cookies to understand how it is used.</p></div><div className="cookie-actions"><a href="#">Cookie settings</a><label htmlFor="cookie-dismiss">Accept all</label></div></aside></main>
}
