const pages: Record<string, { title:string; intro:string; features:string[]; hero:string }> = {
  "event-technology": { title:"Products & Services", intro:"Our comprehensive range of event technology products and services can be used individually or combined to meet both simple and complex engagement requirements.", features:["Audience engagement technology","Event design & facilitation","End-to-end event delivery"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/Products-Header-Banner-Woman-with-glasses.jpg" },
  "event-technology/products": { title:"Audience Engagement Technology Products", intro:"Creating and curating engagement for hybrid, virtual and live events", features:["OpenMeet","OpenVOD","OpenTube"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/Products-Header-Banner-Woman-with-glasses.jpg" },
  "openmeet": { title:"Elevate your meetings with our next level audience engagement technology", intro:"OpenMeet, is our gold standard, a fully supported audience engagement technology platform developed for a wide range in person, hybrid and virtual events.", features:["Browser based, highly customisable, user-friendly","A fully managed solution","Dynamic, interactive formats","Support in up to 40 languages"], hero:"https://www.openaudience.com/wp-content/uploads/2023/03/openmeet.jpg" },
  "openvod": { title:"Power-up Your Videos", intro:"Make event video content instantly accessible to busy healthcare professionals using our cutting-edge video on-demand search technology.", features:["Intelligent content search","On-demand access","Branded content hubs","Engagement analytics"], hero:"https://www.openaudience.com/wp-content/uploads/2023/06/openvod.jpg" },
  "opentube": { title:"Create interactive video content for maximum engagement", intro:"Present and share video content, offering a fully customisable and measurable immersive experience for your digital audiences across the globe.", features:["Interactive video","Global delivery","Custom branding","Measurable engagement"], hero:"https://www.openaudience.com/wp-content/uploads/2022/11/Products-OpenTube-Finger-touching-screen.jpg" },
  "event-technology/services": { title:"Services", intro:"We offer a range of complementary event technology services and engagement tools to support our core products.", features:["Agenda Design","Event Registration & Microsites","Content Development","Events Comms","Analytics, Insights & Return on Engagement","Event Management & Marketing"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/services-1.jpg" },
  "event-technology/solutions": { title:"Solutions", intro:"We are always committed to achieving the best possible outcomes for our clients.", features:["Live events","Hybrid programmes","Virtual meetings","Global congresses","Advisory boards","Internal communications"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/solutions-1.jpg" },
  "events/life-sciences": { title:"Better engagement for healthcare professionals, globally.", intro:"We design and deliver meetings, congresses, and educational events that give HCPs a voice, ensure compliance, and create measurable outcomes across 150+ markets.", features:["Compliant engagement","HCP education","Advisory boards","Congress support","Global reach","Measurable outcomes"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/Products-OpenTube-Finger-touching-screen.jpg" },
  "sustainability-at-open-audience": { title:"Sustainability at Open Audience", intro:"As a virtual agency with a low carbon footprint, delivering global events virtually, we are always looking at ways to minimise our impact.", features:["Virtual-first working","Lower travel impact","Sustainable event design","Responsible suppliers"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/sustain-1.png" },
  "blog": { title:"Open Audience Blogs", intro:"Our opinions, perspectives and insights", features:["Rethinking Business and Event Travel: A New Era Post-Pandemic","Navigating the Green Wave: Unpacking the Impact of European Sustainability Laws on Business & Event Travel","To AI or not to AI: Navigating the Role of AI in the Events Industry at Open Audience","How Digital Immersive Experiences Can Help Event Professionals Create Engaging Events","All Registration Experiences are Created Equal, Right?","Is post-event, on-demand viewing now in demand itself?"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/blog-elements.png" },
  "case-studies": { title:"Case Studies", intro:"", features:["Live Surgery Workshops","Global Pharmaceutical Virtual Briefings","Virtual Advisory Board with Pre-Event Survey","3-Day Global Asset Management Conference","Multilingual engagement programmes","Hybrid Medical Education event for HCPs"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/blog-elements.png" },
  "contact": { title:"Contact Us", intro:"", features:["+44 (0) 1296 294136","info@openaudience.com","LinkedIn: Open Audience"], hero:"https://www.openaudience.com/wp-content/uploads/2022/10/blog-elements.png" },
};

function Header(){return <header className="site-header"><a className="brand" href="/"><img src="https://www.openaudience.com/wp-content/uploads/2022/08/logo.svg" alt="Open Audience" /></a><nav aria-label="Primary navigation"><div className="nav-group"><a href="/event-technology/">Products &amp; Services</a><div className="dropdown"><div className="subgroup"><a href="/event-technology/products/">Products <span>›</span></a><div className="flyout"><a href="/openmeet/">OpenMeet</a><a href="/openvod/">OpenVOD</a><a href="/opentube/">OpenTube</a></div></div><a href="/event-technology/services/">Services</a></div></div><a href="/event-technology/solutions/">Solutions</a><a href="/events/life-sciences/">Life Sciences</a><div className="nav-group"><a href="#">More</a><div className="dropdown"><a href="/sustainability-at-open-audience/">Sustainability at Open Audience</a><a href="/blog/">Blog</a><a href="/case-studies/">Case Studies</a></div></div><a href="/contact/">Contact</a></nav><a className="mobile-contact" href="/contact/">Contact</a></header>}
function Footer(){return <footer><div className="section footer-grid"><div><a className="brand brand-white" href="/"><img src="https://www.openaudience.com/wp-content/themes/open-audience_1_2/svg/logo-white.svg" alt="Open Audience" /></a></div><div><h4>Sign up for our newsletter</h4><a href="mailto:info@openaudience.com?subject=Newsletter%20sign-up">Sign up →</a></div><div><h4>Links</h4><a href="#">Privacy Policy</a><a href="#">Cookies Policy</a></div><div><h4>Contact</h4><a href="tel:01296294136">+44 (0) 1296 294136</a><a href="mailto:info@openaudience.com">info@openaudience.com</a></div></div><div className="copyright section">© Open Audience 2024</div></footer>}

export default async function ContentPage({params}:{params:Promise<{slug:string[]}>}){
  const key=(await params).slug.join("/"); const page=pages[key]||pages["event-technology"];
  return <main><Header/><section className="inner-hero" style={{backgroundImage:`linear-gradient(rgba(5,22,75,.35),rgba(5,22,75,.35)),url(${page.hero})`}}><div className="section"><h1>{page.title}</h1>{page.intro ? <p>{page.intro}</p> : null}</div></section><section className="section content-section"><div className="feature-grid">{page.features.map((f,i)=><article key={f}><span>0{i+1}</span><h3>{f}</h3></article>)}</div></section><section className="contact-banner"><div className="section contact-inner"><p className="eyebrow light">CONTACT US</p><h2>Book a<br/>conversation today</h2><p>We would love to talk to you about your audience engagement challenges</p><a className="button button-blue" href="mailto:info@openaudience.com">Get in touch</a></div></section><Footer/><input className="cookie-toggle" type="checkbox" id="cookie-dismiss"/><input className="settings-toggle" type="checkbox" id="cookie-settings"/><aside className="cookie-banner"><p>This site uses cookies. By continuing to browse the site, you are agreeing to our use of cookies.</p><div className="cookie-actions"><label htmlFor="cookie-dismiss">Accept settings</label><label htmlFor="cookie-dismiss">Hide notification only</label><label htmlFor="cookie-settings">Settings</label></div></aside><section className="cookie-modal"><div><label className="modal-close" htmlFor="cookie-settings">×</label><h3>Cookie and Privacy Settings</h3><h4>How we use cookies</h4><p>We may request cookies to be set on your device. We use cookies to let us know when you visit our websites, how you interact with us, to enrich your user experience, and to customize your relationship with our website.</p><h4>Essential Website Cookies</h4><p>These cookies are strictly necessary to provide you with services available through our website and to use some of its features.</p><h4>Other external services</h4><p>We also use different external services like Google Webfonts, Google Maps, and external video providers.</p><label className="modal-accept" htmlFor="cookie-dismiss">Accept settings</label></div></section></main>
}
